apiVersion: v1
kind: Service
metadata:
  name: producer-service
  namespace: bktest
spec:
  selector:
    app: producer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
