apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: my-namespace
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3309
      targetPort: 3309
  type: ClusterIP
